build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
    tests:
      tests:
        override:
          - command: ./vendor/bin/phpunit --testsuite unit,functional --coverage-clover clover.xml
            coverage:
              file: clover.xml
              format: 'php-clover'

filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
coding_style:
  php: {  }
