build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
    tests:
      environment:
        docker: true
        variables:
          TEST_TCP_TRANSPORT_URL: 'tcp://localhost:4000'
      tests:
        override:
          - docker run --name jsonrpc --rm -d -p "4000:4000" strider2038/json-rpc-mock-server
          - command: ./vendor/bin/phpunit --coverage-clover clover.xml
            coverage:
              file: clover.xml
              format: 'php-clover'
          - docker stop jsonrpc

filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true
coding_style:
  php: {  }
